### ISSUE TITLE
Migrate documentation from Markdown to RST

### ISSUE THREAD

**Issue by openvmp** [openvmp/partcad#82]
Copy all of the content from the top level README.md into the docs/ folder so that it's published on readthedocs.
Keep the top level README.md simple and concise, focused on listing the features with links to readthedocs for each feature.

**Comment by AbdoALPOP** [comment]
👋 Hey @openvmp ,

I am interested in your task and available to start immediately.

I am experienced with [Docusaurus.io](http://docusaurus.io/), [Nextra](https://nextra.site/), [Mkdocs](http://mkdocs.org/), and markdown. I can provide you with a user-friendly guide.

Here are some of my live guides:
- [Redstone](https://docs.redstone.finance/docs/introduction)
- [RHQ](https://documentation-orhp.vercel.app/)
- [WashMaster User Guide](https://help.dev.washmaster.ch/)

I'm looking forward to hearing from you soon 😃
[Contact me](mailto:abdoprogrammer55@gmail.com) and let's get started.

**Comment by openvmp** [comment]
Hi Abdelrahman,

Thank you for reaching out to me.

Is there anything I can clarify in the task?
How is Upwork working for you?
Please, let me know how I can help.

Thank you
Roman

**Comment by AbdoALPOP** [comment]
Hello @openvmp,
Here is my [Upwork profile](https://www.upwork.com/freelancers/~0150cd1a613b4cc68e)
Please send me a message there and let's get started.

**Comment by openvmp** [comment]
Done
